mRNA = read.csv("mRNA.lengths",sep="\t",header=T,row.names=1)
TE = read.csv("transposon.lengths",sep="\t",header=T,row.names=1)
summary(mRNA)
summary(TE)
pdf("lengths_hist.pdf")
hist(TE$Length)
hist(TE$Length,100,main="TE length distribution")
hist(mRNA$Length,100,main="mRNA length distribution")

short = subset(mRNA,mRNA$Length < 10000)
summary(short)
hist(short$Length,100,main="shorter mRNA length distribution")
long = subset(mRNA,mRNA$Length > 50000)
summary(long)
long
